### ISSUE TITLE
Add option to set class for active page

### ISSUE THREAD

**Issue by roland-d** [stephweb/daw-php-pagination#1]
Hello,

Thank you for this library. It is very easy to work with. There is one "issue" I am running into. The class for the active page is hardcoded to `active`. Is it possible to make this a configuration option as well? Thank you for your consideration.

**Comment by stephweb** [comment]
Hello.

Thank you for your message.
I just added this possibility:

For change the CSS class of the active link :
`$pagination = new Pagination(['css_class_link_active'=>'name-css-class-of-link-active']);`
(the CSS class name is by default "active")

**Comment by roland-d** [comment]
@stephweb Thank you so much for your quick response. I have test this and all works great. Have a happy New Year :)
